language: go
sudo: required
dist: trusty
go:
- 1.10.1
env:
- GOMAXPROCS=4
os:
- linux
install:
- go get github.com/stretchr/testify/assert
- go get -u golang.org/x/sys/...
- go get github.com/fsnotify/fsnotify
- go get github.com/hpcloud/tail/...
script:
- go test -v -coverprofile=c0.out -cpuprofile cpu.prof -memprofile mem.prof -covermode=atomic
  github.com/mchirico/firewall/utils
- go test -race -v -coverprofile=c1.out -covermode=atomic github.com/mchirico/firewall/watch
- go test -race -v  -coverprofile=c2.out -covermode=atomic github.com/mchirico/firewall/fixtures
before_install:
- openssl aes-256-cbc -K $encrypted_7bee5ceae7dc_key -iv $encrypted_7bee5ceae7dc_iv
  -in fixtures/stage.tar.enc -out fixtures/stage.tar -d
- cd fixtures && tar xvf stage.tar

- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_success:
- cat c0.out c1.out c2.out > c.out
- cp c.out coverage.txt
- bash <(curl -s https://codecov.io/bash)
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
